phpclassic/php-shopify

README.md

Accroding to the `lib/Webhook.php`, the WebHook string is README.md should be `Webhook` instead of `WebHook`. Otherwise, the `ShopifySDK` throws "Invalid resource name WebHook. Pls check the API Reference to get the appropriate resource name." exception.

Change the WebHook into Webhook in README.md

---

.gitignore
lib/CurlRequest.php
lib/HttpRequestJson.php

Hi
In our application we can have multiple processes connecting to Shopify simultaneously.  In this case the approach currently taken to manage the leaky bucket rate limit doesn't work and 429 errors can be thrown.  An alternative approach is to catch the 429 and back off for 0.5 seconds and try again.  This works well for us for those times when a small flurry of parallel connection exhaust the bucket.
Regards
Steve

Better approach to leaky bucket rate limit

---

lib/AuthHelper.php

I need that the AuthHelper accept all the parameters available in the official call url. So I added $state and $options variable to the createAuthRequest method sign (with null default) and passed to the $authUrl construction.
https://{shop}.myshopify.com/admin/oauth/authorize?client_id={api_key}&scope={scopes}&redirect_uri={redirect_uri}&state={nonce}&grant_options[]={option}

Added $state and $options parameters to $authUrl

---

lib/CurlRequest.php

When making many requests over a short period we have noticed Shopify's API sometimes returns a 403 Forbidden error response for requests that usually work.
I have researched this and believe the requests are being caught by some kind of automated request filtering system on Shopify's servers.
Adding a User-Agent header to all CURL requests resolves this issue. I guess their automated system sees the User-Agent header and assumes it is a valid request instead of some sort of scraper.
Relevant discussion: https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/suddenly-getting-forbidden-request-error-from-shopify-with-curl-411472

Add User-Agent header to CURL requests

---

README.md

graphql can be used with private apps.

Updated readme. Using graphql with private apps.

---

composer.json
lib/GraphQL.php
lib/HttpRequestGraphQL.php
lib/HttpRequestJson.php

Shopify API supports passing graphql-query with variables as separate field (https://help.shopify.com/en/api/getting-started/shopify-and-graphql/variables#variables-in-curl), but here was no options to do that.
I've added new parameter to `GraphQL::post()` and done neccessary changes in `HttpRequestGraphQL::prepareRequest()` to use correct `Content-type` header.

Add parameter $variables to the GraphQL::post()

---

lib/GraphQL.php
lib/HttpRequestJson.php
lib/ShopifyResource.php

Shopify has a really good policy regarding errors and error codes described here: https://help.shopify.com/en/api/getting-started/response-status-codes (Pretty sure some of the contributors read it since 429 is mentioned in code).
The problem is that the errors ar thrown without the code. That in turn forces ppl to keep using stuff like stripos($response, '[API] Invalid API key or access token') to be able to catch exceptions and treat them. This is results in unnecessary maintenance (especially if for some reason shopify decide to change a message text). Another option would be to call the CurlRequest::$lastHttpCode from outside the php-shopify code, but that would couple the lib into the project and I don't think I need to mention why that is bad :).
I added the last http response code …

Added last http code as exception code

---

lib/ShopifyResource.php

Adding support for cursor pagination. 
example usage:
```
$productResource =  $shopify->getApi()->Product();
$products = $productResource->get(['limit'=>50]);
$nextPageProducts = $productResource->get($productResource->getNextPageParams());
/* in short: you need to reuse the resource to get the params before making another resource */**
```

add support for handling cursor pagination in API 2019-07+

---

lib/CurlRequest.php
lib/ShopifyResource.php

This is an attempt to implement the same logic from #125 but without breaking backwards-compat.

Add support for cursor based pagination (again)

---

lib/ShopifyResource.php

The previous link was not getting assigned to `prevLink` property in the `ShopifyResource` class.
Also, var_dump statement removed from `getLink` Method in `ShopifyResource` class.

Bug solved for previous link in ShopifyResounce

---

lib/CurlResponse.php

Since http2 header field names must be lowercase ( https://httpwg.org/specs/rfc7540.html#HttpHeaders ) but if curl uses a lower http version the field names are in mixed case. I noticed as on our live system the prev. and next links couldn't be found as with http1.1 they're in the field `Link` instead of `link`. So it makes sense to always make sure they're lower case for consistency.

Make sure header keys are always lowercase

---

lib/Collection.php
lib/ShopifySDK.php
tests/CollectionTest.php

Collection is available in Api version 2020-01
see https://shopify.dev/docs/admin-api/rest/reference/products/collection

Added the Collection resource

---

lib/ShopifyResource.php

Shopify sends back a HTTP code of 204 on a successful delete.

Added delete status of 204

---

lib/PriceRule.php

The shopify API supports the count resource on the pricerule endpoint: https://shopify.dev/docs/admin-api/rest/reference/discounts/pricerule?api[version]=2020-04#count-2020-04

price rule endpoint supports count

---

README.md
lib/Dispute.php
lib/ShopifyPayment.php
lib/ShopifyResource.php
lib/ShopifySDK.php

- Added Resource for [ShopifyPayments Dispute](https://shopify.dev/docs/admin-api/rest/reference/shopify_payments/dispute?api[version]=2020-01)
- Added $httpCode pass-thru when throwing CurlException (required as dispute endpoint responds with 404 where there are no dispute in store)

Added ShopifyPayment Dispute resource

---

lib/Refund.php

When I pass in the array, I get a warning in my IDE since it's not defined in this class. So I updated the definition.

calculate() takes an optional array as a parameter.

---

README.md
lib/ShopifyResource.php

Hi,
Shopify now asks for some headers for certain new features (i.e: price presentment for Product Variant https://shopify.dev/docs/admin-api/rest/reference/products/product-variant?api[version]=2020-04 ) I'm guessing that they will add more features that could be activated using that HTTP header.
I have added this in my app since I needed it. Not sure if others would find this useful too?

Add Shopify API headers as a config to the SDK

---

lib/CurlRequest.php

This PR uses the `Retry-After` header provided from Shopify in a 429 Too Many Requests response as the amount of time to sleep before retrying the request.
When using the hard-coded value of 0.5 seconds an infinite loop can occur because if the Retry-After value is higher than this, Shopify will keep rejecting the request with a 429 error.
This PR needs #183 to be merged to work properly.

Use Retry-After header as value to sleep for before retrying request

---

lib/CurlResponse.php

As discussed, #143 lowercases all headers in CurlResponse. This is a breaking change which stops the following from working:
https://github.com/phpclassic/php-shopify/blob/a233b8d6e22e651402ef2e440b9433aa704146b8/lib/CurlRequest.php#L163
This PR lowercases the given key in the CurlResponse::getHeader method before checking if it is set.

Fix bug introduced by #143 by lowercasing key in getHeader

---

lib/Batch.php
lib/PriceRule.php

Add support for creating DiscountCodes on a PriceRule via the Batch action:
```php
$api->PriceRule($priceRuleId)->Batch()->post([
['code' => 'ABC'],
['code' => 'BCD'],
['code' => 'CDE'],
])
```

Support DiscountCode batch Action

---

README.md
lib/Cart.php
lib/ShopifySDK.php

The `Cart` resource is read only, where you can provide the cart_token to retrieve the Shopify cart object.
Example: `$shopify->Cart('1d19a32178501c44ef2223d73c54d16d')->get()`
Example Response: 
```
{
"token": "1d19a32178501c44ef2223d73c54d16d",
"note": null,
"attributes": {},
"total_price": 0,
"total_weight": 0,
"item_count": 0,
"items": [],
"requires_shipping": false,
"currency": "CAD"
}
```
You can retrieve the cart token on your website by using the following javascript snippet: 
`var cart_token = (document.cookie.match('(^|; )cart=([^;]*)') || 0)[2];`
I'm sorry I didn't provide any tests because this is really a shop specific resource request.  I did test the cart resource using my own shop and credentials and it worked just fine. 
I'm not completely versed in the library and might …

Added the Cart Resource

---

lib/AuthHelper.php

Rather than returning null if the access token request fails, the `getAccessToken()` method in `AuthHelper.php` should throw an `SdkException` so that when the method is invoked in a try-catch the developer can choose how to act upon a bad request (usually HTTP 400).
This can happen when trying to request an access token twice with the same authorisation code, which can happen if the user installing the Shopify app refreshes the callback route. The user might do this by accident, by using page navigation in their browser or when the developers app crashes on that route. If this does happen, then the developer may choose to redirect them back to Shopify safely, rather than trying to move ahead with using a null access token.

Throw an exception if the access token request failed

---

lib/ShopifyResource.php

A useful fix for endpoints such as discount code lookup, which returns a 303 HTTP status code along with a header indicating the full URI of the discount code on the shop.
See more: https://shopify.dev/docs/admin-api/rest/reference/discounts/discountcode#lookup-2021-01

Return location header as array if response is 303

---

lib/AuthHelper.php

When we use one page for authorize and redirect_uri, we have a problem with autogenerated query params, such as hmac and etc.
So Shopify throw an error that redirect_uri is not whitelisted. But we cannot whitelist such url.
I suggest to simply remove these query params from redirect_uri.

Remove query params from current url

---

lib/FulfillmentOrder.php
lib/Order.php

Only the section that can be called from the order id using the URL
GET /admin/api/2021-04/orders/{order_id}/fulfillment_orders.json
Is complete. I have tested it and it works on my project and is helpful when getting orders from shopify and determining where they will need to be fulfilled

Adding Fulfillment Order

---

lib/FulfillmentOrder.php
lib/ShopifySDK.php

- added `hold` and `release_hold` methods introducted in version [2021-10](https://shopify.dev/api/admin-rest/2021-10/resources/fulfillmentorder#[post]/admin/api/2021-10/fulfillment_orders/{fulfillment_order_id}/hold.json)
- added `FulfillmentOrder` as top level resource

FulfillmentOrder hold and release_hold methods

---

lib/HttpRequestGraphQL.php
lib/HttpRequestJson.php
lib/ShopifyResource.php

Sometime for temporary issue, shopify http request fail, for example I found in my test logs:
```
Request failed with HTTP Code 520
Request failed with HTTP Code 503
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```
If you try again a moment later, same requests are ok.
This implementation try to mitigate this problem.
I add a configuration parameters `RequestRetryCallback` that allow to define a callback to manage or log the retry.
The callback take 3 input parameter: raw curl response, exception object and retry number. 
If this callback return true (or non null value) another attempt will be performed.
By default this callback is not defined and this does not change the original behavior of the library.
For example
```php
PHPShopify\ShopifySDK::config([
'ShopUrl' => SHOPIFY_URL, …
```

resend requests that returns http error

---

lib/SmartCollection.php

SmartCollection has Metafield support, but static analysis will complain unless it is described in the docblock.

Add Metafield property and method to docblock

---

lib/Collection.php
lib/DraftOrder.php

Collection & DraftOrder api is now support Metafield
see: https://shopify.dev/api/admin-rest/2022-07/resources/metafield

Metafield as a child resource of Collection & DraftOrder

---

lib/Fulfillment.php
lib/ShopifySDK.php

- https://github.com/phpclassic/php-shopify/commit/8b2c2a09e6bed833f7b73eed2e4b6107fcbd0f4a I just added `update_tracking` action for fulfillment
- https://github.com/phpclassic/php-shopify/commit/4d49e3bdfaaea01c5234285391bb0e0c23f3ad91 Some Fulfillment api can be call as parent resource now, so we should enable it, related #268 
> POST /admin/api/2022-07/fulfillments.json
> POST /admin/api/2022-07/fulfillments/1069019872/cancel.json
> POST /admin/api/2022-07/fulfillments/1069019871/update_tracking.json
see: https://shopify.dev/api/admin-rest/2022-07/resources/fulfillment

Fulfillment 2022-07 API version

---

README.md
lib/ApiDeprecations.php
lib/ShopifySDK.php

I have added a new Shopify API Resource to retrieve the Shopify API Deprecations that Shopify has logged in their system.  This is helpful for developers to stay up to date with deprecations that are coming up in the future.  The resource returns an array of API deprecations example: 
```
[0]=>
array(8) {
["api_type"]=>
string(4) "REST"
["description"]=>
string(83) "Some customer fields have been deprecated from the Admin REST API's Order resource."
["documentation_url"]=>
string(88) "https://shopify.dev/changelog/property-deprecations-in-the-rest-admin-api-order-resource"
["endpoint"]=>
string(5) "Order"
["last_call_at"]=>
string(27) "2022-12-13T16:59:32.000000Z"
["migration_deadline"]=>
string(27) "2023-04-01T15:00:00.000000Z"
["graphql_schema_name"]=>
NULL
["version"]=>
string(7) …
```

Feature - Added API Deprecations Resource

---

README.md
lib/FulfillmentOrder.php
lib/FulfillmentRequest.php
lib/Order.php

This pull request aims to support the behavior required by:
https://shopify.dev/apps/fulfillment/order-management-apps/manage-fulfillments#request-a-fulfillment
https://shopify.dev/api/admin-rest/2022-10/resources/assignedfulfillmentorder
+ FulfillmentRequest Resource - including actions
+ Mapped FulfillmentOrder->FulfillmentRequest 
+ Mapped Order(id)->FulfillmentOrder
Example:
```php
// Requesting the FulfilmentOrder for a given order
$fo = $client->Order("1234567890")->FulfillmentOrder()->get();
// Creating a FulfilmentRequest
// Follow instructions to get partial fulfilments
$fr = $client->FulfillmentOrder('0987654321')->FulfillmentRequest->post([]);
// Accepting \ Rejecting a FulfilmentRequest
$fr = $client->FulfillmentOrder('0987654321')->FulfillmentRequest->accept();
$fr = …
```

add support for Order()->FulfillmentOrder and FulfillmentRequests

---

README.md
lib/AssignedFulfillmentOrder.php
lib/ShopifySDK.php

This pull request supports the AssignedFulfillmentOrder resource:
https://shopify.dev/docs/api/admin-rest/2023-04/resources/assignedfulfillmentorder
AssignedFulfillmentOrder Resource
Example:
```php
// Requesting all assigned fulfillment orders
$shopify->AssignedFulfillmentOrder()->get();
// Requesting assigned fulfillment orders (by status)
$shopify->AssignedFulfillmentOrder()->get(["assignment_status" => "fulfillment_requested"]);
// Requesting assigned fulfillment orders (by locations)
$shopify->AssignedFulfillmentOrder()->get(["location_ids" => ["123456789"]]);
```

Add support for AssignedFulfillmentOrder resource

---

lib/CurlRequest.php

Currently, it is not possible to see the past sleep time due to rate limit exceeded during multiple requests of an integration flow. With this modification, it is possible to call the static variable "CurlRequest::$totalRetrySleepTime" from outside in order to know the actual total time spent in sleep.

Add total time spent in sleep during multiple requests

---

README.md
lib/GiftCard.php
lib/GiftCardAdjustment.php
lib/ShopifySDK.php

Added the Gift Card Adjustment Resource to list adjustments and increment and decrement amounts on gift cards.
This is a Shopify Plus only feature and requires you to contact Shopify Support to enable the `gift_card_adjustments` access scope. 
API Documentation - https://shopify.dev/docs/api/admin-rest/2023-01/resources/gift-card-adjustment
**Usage**
```php
$config = array(
'ShopUrl' => 'my-store.myshopify.com',
'AccessToken' => 'shpat_999999999999999999999'
);
$shopify = \PHPShopify\ShopifySDK::config($config);
$gift_card_id = 88888888888;
$gift_card_adjustment_id = 999999999999;
// Get all gift card adjustments
$shopify->GiftCard($gift_card_id)->Adjustment()->get();
// Get a single gift card adjustment
$shopify->GiftCard($gift_card_id)->Adjustment($gift_card_adjustment_id)->get();
// …
```

Gift Card Adjustment Resource

---

lib/HttpRequestGraphQL.php

Details : https://shopify.dev/changelog/content-type-application-graphql-is-deprecated
https://shopify.dev/docs/api/release-notes/2025-01

Content type application/graphql is deprecated

---

lib/HttpRequestGraphQL.php

fixed the 400 bad request api issue with graphql when variables are not passed even if they are not required.

Fixed 400 Bad Request Api Issue with Graphql
